<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase" tests="2" time="72.040" ignored="6" failures="1" timestamp="11 Nov 2019 11:40:07 GMT" skipped="0" hostname="probs-165" errors="0">
  <testcase name="TC8_verify_NoMatchingRecords" time="35.108" classname="com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase">
    <failure type="java.lang.AssertionError" message="The expected text contains the actual Not Matching Records Found">
      <![CDATA[java.lang.AssertionError: The expected text contains the actual Not Matching Records Found
	at org.junit.Assert.fail(Assert.java:88)
	at com.protech.selenium.api.base.SeleniumBase.verifyPartialText(SeleniumBase.java:1558)
	at com.protech.nvkids.pages.bstl.BatchStatusLogsPage.verifyNoMatchRecords(BatchStatusLogsPage.java:276)
	at com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase.TC8_verify_NoMatchingRecords(BatchStatusLogsTestcase.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1289)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC8_verify_NoMatchingRecords -->
  <testcase name="TC9_verify_SuccesfulInquiry" time="36.932" classname="com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase"/>
  <testcase name="stopReport" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- stopReport -->
  <testcase name="stopReport" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- stopReport -->
  <testcase name="Deleteimages" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- Deleteimages -->
  <testcase name="Deleteimages" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- Deleteimages -->
  <testcase name="startReport" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- startReport -->
  <testcase name="startReport" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- startReport -->
</testsuite> <!-- com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase -->
