<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.protech.nvkids.testcases.bstl.PrintQueueErrorsTestcase" tests="12" time="451.445" ignored="6" failures="1" timestamp="18 Nov 2019 06:23:00 GMT" skipped="0" hostname="probs-165" errors="0">
  <testcase name="TC32_verify_CopyPasteAllowance" time="36.572" classname="com.protech.nvkids.testcases.bstl.PrintQueueErrorsTestcase"/>
  <testcase name="TC24_VerifyCharAllowance_NegativeScenario" time="37.006" classname="com.protech.nvkids.testcases.bstl.PrintQueueErrorsTestcase"/>
  <testcase name="TC26_verifyNullProcessDate" time="35.831" classname="com.protech.nvkids.testcases.bstl.PrintQueueErrorsTestcase"/>
  <testcase name="TC23_VerifyCharAllowance_PositiveScenario" time="40.333" classname="com.protech.nvkids.testcases.bstl.PrintQueueErrorsTestcase"/>
  <testcase name="TC22_verifyfieldspresent" time="30.483" classname="com.protech.nvkids.testcases.bstl.PrintQueueErrorsTestcase"/>
  <testcase name="TC28_verifyValidation_VerifyFutureProcessDate" time="37.467" classname="com.protech.nvkids.testcases.bstl.PrintQueueErrorsTestcase"/>
  <testcase name="TC32_verify_VerifySuccessfulInquiry" time="38.905" classname="com.protech.nvkids.testcases.bstl.PrintQueueErrorsTestcase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.fail(Assert.java:95)
	at com.protech.selenium.api.base.SeleniumBase.VerifyGridHasData(SeleniumBase.java:2285)
	at com.protech.nvkids.pages.bstl.PrintQueueErrorsPage.VerifySucessfulInquiry(PrintQueueErrorsPage.java:260)
	at com.protech.nvkids.testcases.bstl.PrintQueueErrorsTestcase.TC32_verify_VerifySuccessfulInquiry(PrintQueueErrorsTestcase.java:130)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC32_verify_VerifySuccessfulInquiry -->
  <testcase name="TC31_verify_NoMatchingRecords" time="40.371" classname="com.protech.nvkids.testcases.bstl.PrintQueueErrorsTestcase"/>
  <testcase name="TC30_verifyInvalidNoticeID" time="40.617" classname="com.protech.nvkids.testcases.bstl.PrintQueueErrorsTestcase"/>
  <testcase name="TC25_VerifyFieldsLength" time="35.757" classname="com.protech.nvkids.testcases.bstl.PrintQueueErrorsTestcase"/>
  <testcase name="TC27_verifyInvalidProcessDate" time="37.923" classname="com.protech.nvkids.testcases.bstl.PrintQueueErrorsTestcase"/>
  <testcase name="TC29_verifyInvalidCaseID" time="40.180" classname="com.protech.nvkids.testcases.bstl.PrintQueueErrorsTestcase"/>
  <testcase name="stopReport" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- stopReport -->
  <testcase name="stopReport" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- stopReport -->
  <testcase name="Deleteimages" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- Deleteimages -->
  <testcase name="Deleteimages" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- Deleteimages -->
  <testcase name="startReport" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- startReport -->
  <testcase name="startReport" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- startReport -->
</testsuite> <!-- com.protech.nvkids.testcases.bstl.PrintQueueErrorsTestcase -->
