<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite name="com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase" tests="13" time="500.269" ignored="6" failures="4" timestamp="18 Nov 2019 06:23:00 GMT" skipped="0" hostname="probs-165" errors="0">
  <testcase name="TC5_Inquirewith_nullFromDate" time="31.028" classname="com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase"/>
  <testcase name="TC6_Inquirewith_InvalidFromDate" time="32.247" classname="com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase"/>
  <testcase name="TC8_InquireWith_FutureFromDate" time="33.265" classname="com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase"/>
  <testcase name="TC9_InquireWith_FutureThroughDate" time="35.983" classname="com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase"/>
  <testcase name="TC11_verify_NoMatchingRecords" time="56.233" classname="com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase">
    <failure type="java.lang.AssertionError" message="The expected text doesn&#039;t contain the actual No Matching Records Found">
      <![CDATA[java.lang.AssertionError: The expected text doesn't contain the actual No Matching Records Found
	at org.junit.Assert.fail(Assert.java:88)
	at com.protech.selenium.api.base.SeleniumBase.verifyPartialText(SeleniumBase.java:1616)
	at com.protech.nvkids.pages.bstl.BatchStatusLogsPage.verifyNoMatchRecords(BatchStatusLogsPage.java:278)
	at com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase.TC11_verify_NoMatchingRecords(BatchStatusLogsTestcase.java:109)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC11_verify_NoMatchingRecords -->
  <testcase name="TC4_VerifyFieldsLength" time="31.442" classname="com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase"/>
  <testcase name="TC10_verifyValidation_VerifygGreaterThroughDate" time="58.984" classname="com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase">
    <failure type="java.lang.AssertionError" message="The expected text doesn&#039;t contain the actual Through Date Must be Greater than or Equal to From Date">
      <![CDATA[java.lang.AssertionError: The expected text doesn't contain the actual Through Date Must be Greater than or Equal to From Date
	at org.junit.Assert.fail(Assert.java:88)
	at com.protech.selenium.api.base.SeleniumBase.verifyPartialText(SeleniumBase.java:1616)
	at com.protech.nvkids.pages.bstl.BatchStatusLogsPage.verifyGreaterThroughDate(BatchStatusLogsPage.java:264)
	at com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase.TC10_verifyValidation_VerifygGreaterThroughDate(BatchStatusLogsTestcase.java:101)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC10_verifyValidation_VerifygGreaterThroughDate -->
  <testcase name="TC1_verifyfieldspresent" time="54.250" classname="com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase">
    <failure type="java.lang.AssertionError" message="The element is not accessible">
      <![CDATA[java.lang.AssertionError: The element is not accessible
	at org.junit.Assert.fail(Assert.java:88)
	at com.protech.selenium.api.base.SeleniumBase.click(SeleniumBase.java:236)
	at com.protech.nvkids.pages.bstl.BatchStatusLogsPage.verifyFieldsPresent(BatchStatusLogsPage.java:114)
	at com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase.TC1_verifyfieldspresent(BatchStatusLogsTestcase.java:29)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC1_verifyfieldspresent -->
  <testcase name="TC12_verify_CopyPasteAllowance" time="30.527" classname="com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase"/>
  <testcase name="TC3_VerifyCharAllowance_NegativeScenario" time="33.692" classname="com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase"/>
  <testcase name="TC2_VerifyCharAllowance_PositiveScenario" time="31.349" classname="com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase"/>
  <testcase name="TC12_verify_SuccesfulInquiry" time="36.887" classname="com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase">
    <failure type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:86)
	at org.junit.Assert.fail(Assert.java:95)
	at com.protech.selenium.api.base.SeleniumBase.VerifyGridHasData(SeleniumBase.java:2285)
	at com.protech.nvkids.pages.bstl.BatchStatusLogsPage.verifySuccesfulInquiry(BatchStatusLogsPage.java:296)
	at com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase.TC12_verify_SuccesfulInquiry(BatchStatusLogsTestcase.java:116)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:104)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:645)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:851)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1177)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at org.testng.TestRunner.privateRun(TestRunner.java:756)
	at org.testng.TestRunner.run(TestRunner.java:610)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:387)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:382)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1293)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1218)
	at org.testng.TestNG.runSuites(TestNG.java:1133)
	at org.testng.TestNG.run(TestNG.java:1104)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
    </failure>
  </testcase> <!-- TC12_verify_SuccesfulInquiry -->
  <testcase name="TC7_Inquirewith_InvalidToDate" time="34.382" classname="com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase"/>
  <testcase name="stopReport" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- stopReport -->
  <testcase name="stopReport" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- stopReport -->
  <testcase name="Deleteimages" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- Deleteimages -->
  <testcase name="Deleteimages" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- Deleteimages -->
  <testcase name="startReport" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- startReport -->
  <testcase name="startReport" classname="utils.Reporter">
    <skipped/>
  </testcase> <!-- startReport -->
</testsuite> <!-- com.protech.nvkids.testcases.bstl.BatchStatusLogsTestcase -->
